name: BedrockTechnology
author: CTimet
description: A generic Slimefun4-Addon
main: io.github.ctimet.bedrocktechnology.BektMain
website: https://github.com/CTimet/BedrockTechnology
version: ${project.version}
api-version: 1.17
depend:
- Slimefun

commands:
  bedrocktechnology:
    aliases:
      - "bekt"
    usage:
      "§4[BEKT-Command]>> e"
    description: "核心指令"
    permission: none
    permission-message: ""