name: BedrockTechnology-BEKT

author: BEKT Development Team

description: A generic Slimefun4-Addon

main: io.github.ctimet.bekt.BektMain

website: https://github.com/CTimet/BEKT

version: beta-1.0.0

api-version: 1.16

depend:
- Slimefun