name: BedrockTechnology--BEKT

author: CTimet

description: A generic Slimefun4-Addon

main: me.CTimet.bekt.BektMain

website: https://github.com/CTimet/BEKT

version: ${project.version}

api-version: 1.16

depend:
- Slimefun