name: BedrockTechnology
author: BEKT Development Team
description: A generic Slimefun4-Addon
main: io.github.ctimet.bedrocktechnology.BektMain
website: https://github.com/CTimet/BedrockTechnology
version: 1.0-beta-220809f0
api-version: 1.17
depend:
- Slimefun

commands:
  bedrocktechnology:
    aliases:
      - "bekt"
    usage:
      "§4[BedrockTechnology] >> 你刚刚输入了错误的指令，如果你想获取指令帮助，可使用/bekt help 来获取帮助"
    description: "核心指令"
    permission: none
    permission-message: ""