name: BedrockTechnology
author: BEKT Development Team
description: A generic Slimefun4-Addon
main: io.github.ctimet.bedrocktechnology.initial.BektMain
website: https://github.com/CTimet/BEKT
version: v1.0-beta-220402
api-version: 1.16
depend:
- Slimefun

commands:
  bedrocktechnology:
    aliases:
      - "bt"
    usage:
      "§a[BedrockTechnology] >> §e 你刚刚输入了错误的指令，如果你想获取指令帮助，可使用/bt help 来获取帮助"
    description: "核心指令"
    permission: none
    permission-message: ""